// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6myfhDaKBWGBnIERQYbKwJGKDUdzZoUU',
    appId: '1:776449922263:web:eb35982c54d4f6ef964c92',
    messagingSenderId: '776449922263',
    projectId: 'pac-2024-2',
    authDomain: 'pac-2024-2.firebaseapp.com',
    storageBucket: 'pac-2024-2.appspot.com',
    measurementId: 'G-9CDC0NM4W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYUgZRUcWDVTylyEhnTxVjibMCIHZh40',
    appId: '1:776449922263:android:003695bd11df0a6f964c92',
    messagingSenderId: '776449922263',
    projectId: 'pac-2024-2',
    storageBucket: 'pac-2024-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6kX1ldj61ZJd5JWarT6_IrVvNmPdKVM',
    appId: '1:776449922263:ios:47f118da016916c5964c92',
    messagingSenderId: '776449922263',
    projectId: 'pac-2024-2',
    storageBucket: 'pac-2024-2.appspot.com',
    iosBundleId: 'com.example.amvali3dviewer',
  );
}
